apiVersion: apps/v1
kind: Deployment
metadata:
  name: historical-network
  namespace: historical-network
  labels:
    app: historical-network
spec:
  replicas: 2
  selector:
    matchLabels:
      app: historical-network
  template:
    metadata:
      labels:
        app: historical-network
    spec:
      containers:
      - name: historical-network
        image: ${IMAGE_REPOSITORY}/historical-network:${IMAGE_TAG}
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10