apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- istio/virtual-service.yaml
- istio/gateway.yaml

# Define variables that can be substituted
replacements:
- source:
    kind: ConfigMap
    name: image-config
    fieldPath: data.repository
  targets:
  - select:
      kind: Deployment
    fieldPaths:
    - spec.template.spec.containers.[name=historical-network].image
    options:
      create: true
      delimiter: "/"
      index: 0

- source:
    kind: ConfigMap
    name: image-config
    fieldPath: data.tag
  targets:
  - select:
      kind: Deployment
    fieldPaths:
    - spec.template.spec.containers.[name=historical-network].image
    options:
      create: true
      delimiter: ":"
      index: 1