apiVersion: v1
kind: Service
metadata:
  name: historical-network
  namespace: historical-network
  labels:
    app: historical-network
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: historical-network