apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "historical-network.fullname" . }}
  labels:
    {{- include "historical-network.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "historical-network.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "historical-network.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "historical-network.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.application.port }}
              protocol: TCP
          env:
            - name: WIKIPEDIA_SCRAPE_INTERVAL
              value: "{{ .Values.wikipedia.scrapeInterval }}"
            - name: WIKIPEDIA_MAX_DEPTH
              value: "{{ .Values.wikipedia.maxDepth }}"
            - name: WIKIPEDIA_MAX_RELATED
              value: "{{ .Values.wikipedia.maxRelatedPerFigure }}"
            - name: NLP_MODEL
              value: "{{ .Values.nlp.model }}"
            - name: NLP_MIN_RELATIONSHIP_STRENGTH
              value: "{{ .Values.nlp.minRelationshipStrength }}"
            - name: API_ENABLE_CORS
              value: "{{ .Values.api.enableCors }}"
            - name: API_RATE_LIMIT
              value: "{{ .Values.api.rateLimit }}"
            - name: SEED_FIGURES
              value: "{{ join "," .Values.wikipedia.seedFigures }}"
          volumeMounts:
            - name: data
              mountPath: /app/data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "historical-network.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
