
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: historical-network
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jbrcoleman/historic-network.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: historical-network
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false